import { makeAutoObservable } from "mobx";

import { IPerk } from "../entities/Perk";

class Agility {
  perkList: IPerk[] = [
    {
      perkId: "actionBoy",
      cost: 1,
      totalAmountOfStars: 3,
      description: "Ваши очки действия восстанавливаются на 15% быстрее",
      title: "Живчик",
      levelRequirment: 2,
      iconSource: "",
      modificator: 15,
      modificatorStep: 15,
      selectedStars: 0,
    },
    {
      perkId: "gunslinger",
      cost: 1,
      totalAmountOfStars: 3,
      description:
        "Ваши неавтоматические пистолеты наносят на 15% больше урона",
      title: "Дуэлист",
      levelRequirment: 2,
      iconSource: "",
      modificator: 10,
      modificatorStep: 5,
      selectedStars: 0,
    },
    {
      perkId: "bornSurvivor",
      cost: 1,
      totalAmountOfStars: 3,
      description:
        "Когда ваше здоровье падает ниже 20% вы автоматически принимаете стимпак каждые 20 секунд",
      title: "Прирождённый выживальщик",
      levelRequirment: 3,
      iconSource: "",
      modificator: 20,
      modificatorStep: 10,
      selectedStars: 0,
    },
    {
      perkId: "gunRunner",
      cost: 1,
      totalAmountOfStars: 2,
      description:
        "Ваша скорость бега увеличена на 10%, когда вы экипированы пистолетом",
      title: "Поставщик оружия",
      levelRequirment: 4,
      iconSource: "",
      modificator: 10,
      modificatorStep: 10,
      selectedStars: 0,
    },
    {
      perkId: "movingTarget",
      cost: 1,
      totalAmountOfStars: 2,
      description:
        "Вы получаете +15 к сопротивлению урону и энергетическому урону пока вы бежите (без силовой)",
      title: "Бегущая мишень",
      levelRequirment: 5,
      iconSource: "",
      modificator: 15,
      modificatorStep: 15,
      selectedStars: 0,
    },
    {
      perkId: "thruHiker",
      cost: 1,
      totalAmountOfStars: 3,
      description: "Вес еды и воды снижен на 30%",
      title: "Походник",
      levelRequirment: 7,
      iconSource: "",
      modificator: 30,
      modificatorStep: 30,
      selectedStars: 0,
    },
    {
      perkId: "deadManSprinting",
      cost: 1,
      totalAmountOfStars: 2,
      description:
        "Вы бежите на 10% быстрее за повышенную стоимость очков действий, когда ваше здоровье ниже 40%",
      title: "Бегущий мертвец",
      levelRequirment: 8,
      iconSource: "",
      modificator: 10,
      modificatorStep: 10,
      sideModificator: 40,
      sideModificatorStep: 10,
      selectedStars: 0,
    },
    {
      perkId: "packingLight",
      cost: 1,
      totalAmountOfStars: 3,
      description: "Ваши пистолеты весят на 25% меньше",
      title: "Гений упаковки",
      levelRequirment: 9,
      iconSource: "",
      modificator: 25,
      modificatorStep: 25,
      selectedStars: 0,
    },
    {
      perkId: "guerilla",
      cost: 1,
      totalAmountOfStars: 3,
      description: "Ваши автоматические пистолеты наносят на 10% больше урона",
      title: "Партизан",
      levelRequirment: 10,
      iconSource: "",
      modificator: 10,
      modificatorStep: 5,
      selectedStars: 0,
    },
    {
      perkId: "marathoner",
      cost: 1,
      totalAmountOfStars: 3,
      description: "Спринт потребляет на 20% меньше очков действия",
      title: "Марафонер",
      levelRequirment: 13,
      iconSource: "",
      modificator: 20,
      modificatorStep: 10,
      selectedStars: 0,
    },
    {
      perkId: "ninja",
      cost: 1,
      totalAmountOfStars: 3,
      description:
        "Скрытые атаки с оружием ближнего боя наносят 2.3х от обычного урона",
      getCustomDescription:
        "Скрытые атаки с оружием ближнего боя наносят 3х от обычного урона",
      title: "Ниндзя",
      levelRequirment: 15,
      iconSource: "",
      modificator: 2.3,
      modificatorStep: 0.3,
      selectedStars: 0,
    },
    {
      perkId: "expertGunslinger",
      cost: 1,
      totalAmountOfStars: 3,
      description:
        "Ваши неавтоматические пистолеты наносят на 10% больше урона",
      title: "Эксперт-стрелок",
      levelRequirment: 15,
      iconSource: "",
      modificator: 10,
      modificatorStep: 5,
      selectedStars: 0,
    },
    {
      perkId: "evasive",
      cost: 1,
      totalAmountOfStars: 3,
      description:
        "Каждое очко ловкости добавляет +1 к урону и сопротивлению энергетическому урону(макс 15)(без силовой брони)",
      title: "Уклончивый",
      levelRequirment: 17,
      iconSource: "",
      modificator: 1,
      modificatorStep: 1,
      sideModificator: 15,
      sideModificatorStep: 15,
      selectedStars: 0,
    },
    {
      perkId: "modernRenegade",
      cost: 1,
      totalAmountOfStars: 3,
      description:
        "Пистолеты получают +15% к точности стрельбы от бедра и 4% шанса сломать конечность",
      title: "Современный ренегад",
      levelRequirment: 18,
      iconSource: "",
      modificator: 15,
      modificatorStep: 15,
      sideModificator: 4,
      sideModificatorStep: 4,
      selectedStars: 0,
    },
    {
      perkId: "sneak",
      cost: 1,
      totalAmountOfStars: 3,
      description:
        "В режиме скрытности вас труднее обнаружить на 25% (без силовой брони)",
      title: "Лазутчик",
      levelRequirment: 20,
      iconSource: "",
      modificator: 25,
      modificatorStep: 25,
      selectedStars: 0,
    },
    {
      perkId: "homeDefense",
      cost: 1,
      totalAmountOfStars: 3,
      description:
        "Вы можете создавать и обезвреживать ловушки, создавать улучшенные турели",
      getDescriptionBasedOnStars: (stars: number) => {
        if (stars === 1) {
          return "Вы можете создавать и обезвреживать ловушки, создавать улучшенные турели";
        }

        if (stars === 2) {
          return "Вы можете создавать и обезвреживать продвинутые ловушки, создавать продвинутые турели";
        }

        if (stars === 3) {
          return "Вы можете создавать и обезвреживать экспертные ловушки, создавать экспертные турели";
        }

        return "";
      },
      title: "На страже родного дома",
      levelRequirment: 22,
      iconSource: "",
      modificator: 1,
      modificatorStep: 1,
      selectedStars: 0,
    },
    {
      perkId: "expertGuerilla",
      cost: 1,
      totalAmountOfStars: 3,
      description: "Ваши автоматические пистолеты наносят на 10% больше урона",
      title: "Эксперт партизан",
      levelRequirment: 25,
      iconSource: "",
      modificator: 10,
      modificatorStep: 5,
      selectedStars: 0,
    },
    {
      perkId: "сovertOperative",
      cost: 1,
      totalAmountOfStars: 3,
      description:
        "Ваши атаки дальнего боя из режима скрытности наносят 2.15x от обычного урона",
      getCustomDescription:
        "Ваши атаки дальнего боя из режима скрытности наносят 2.5x от обычного урона",
      title: "Секретный агент",
      levelRequirment: 27,
      iconSource: "",
      modificator: 2.15,
      modificatorStep: 0.15,
      selectedStars: 0,
    },
    {
      perkId: "lightFooted",
      cost: 1,
      totalAmountOfStars: 1,
      description:
        "Ваше передвижение в режиме скрытности не заставляет ловушки срабатывать",
      title: "Лёгкая поступь",
      levelRequirment: 29,
      iconSource: "",
      modificator: 1,
      modificatorStep: 1,
      selectedStars: 0,
    },
    {
      perkId: "enforcer",
      cost: 1,
      totalAmountOfStars: 3,
      description:
        "Выстрелы из дробовика с 5% шансом могут оглушить цель и с 10% шансом сломать конечность",
      title: "Боец",
      levelRequirment: 30,
      iconSource: "",
      modificator: 5,
      modificatorStep: 5,
      sideModificator: 10,
      sideModificatorStep: 10,
      selectedStars: 0,
    },
    {
      perkId: "goatLegs",
      cost: 1,
      totalAmountOfStars: 2,
      description: "Вы получаете на 40%  меньше урона при падении",
      title: "Козлинные ноги",
      levelRequirment: 32,
      iconSource: "",
      modificator: 40,
      modificatorStep: 40,
      selectedStars: 0,
    },
    {
      perkId: "ammosmith",
      cost: 1,
      totalAmountOfStars: 2,
      description: "Вы производите на 40% больше боеприпасов при изготовлении",
      title: "Мастер боеприпасов",
      levelRequirment: 34,
      iconSource: "",
      modificator: 40,
      modificatorStep: 40,
      selectedStars: 0,
    },
    {
      perkId: "masterGunslinger",
      cost: 1,
      totalAmountOfStars: 3,
      description:
        "Ваши неавтоматические пистолеты наносят на 10% больше урона",
      title: "Мастер дуэлист",
      levelRequirment: 35,
      iconSource: "",
      modificator: 10,
      modificatorStep: 5,
      selectedStars: 0,
    },
    {
      perkId: "escapeArtist",
      cost: 1,
      totalAmountOfStars: 1,
      description:
        "Входите в режим скрытности, чтобы противники потеряли вас из виду, бег более не влияет на скрытность",
      title: "Специалист по побегам",
      levelRequirment: 35,
      iconSource: "",
      modificator: 1,
      modificatorStep: 1,
      selectedStars: 0,
    },
    {
      perkId: "misterSandman",
      cost: 1,
      totalAmountOfStars: 2,
      description:
        "В ночной период времени ваше оружие с глушителем наносит на 50% больше урона в режиме скрытности",
      title: "Специалист по побегам",
      levelRequirment: 37,
      iconSource: "",
      modificator: 50,
      modificatorStep: 50,
      selectedStars: 0,
    },
    {
      perkId: "whiteKnight",
      cost: 1,
      totalAmountOfStars: 3,
      description:
        "Ваша броня приходит в негодность на 20% медленнее и дешевле обходится в починке",
      title: "Белый рыцарь",
      levelRequirment: 39,
      iconSource: "",
      modificator: 20,
      modificatorStep: 20,
      selectedStars: 0,
    },
    {
      perkId: "masterGuerilla",
      cost: 1,
      totalAmountOfStars: 3,
      description: "Ваши автоматические пистолеты наносят на 10% больше урона",
      title: "Мастер партизан",
      levelRequirment: 43,
      iconSource: "",
      modificator: 10,
      modificatorStep: 5,
      selectedStars: 0,
    },
    {
      perkId: "dodgy",
      cost: 1,
      totalAmountOfStars: 3,
      description:
        "С 10% шансом вы можете избежать входящий урон, истратив на это 30 очков действий за каждое попадание по вам",
      title: "Подозрительный",
      levelRequirment: 45,
      iconSource: "",
      modificator: 10,
      modificatorStep: 10,
      selectedStars: 0,
    },
    {
      perkId: "secretAgent",
      cost: 1,
      totalAmountOfStars: 3,
      description: "Используемые вами стелс-бои работают в 2 раза дольше",
      title: "Тайный агент",
      levelRequirment: 47,
      iconSource: "",
      modificator: 2,
      modificatorStep: 1,
      selectedStars: 0,
    },
    {
      perkId: "adrenaline",
      cost: 1,
      totalAmountOfStars: 5,
      description:
        "Вы получаете +6%(макс 36%) к наносимому вами урону, за каждое убийство. Эффект действует в течение 30с",
      title: "Адреналин",
      levelRequirment: 49,
      iconSource: "",
      modificator: 6,
      modificatorStep: 1,
      sideModificator: 36,
      sideModificatorStep: 6,
      selectedStars: 0,
    },
    {
      perkId: "gunFu",
      cost: 1,
      totalAmountOfStars: 3,
      description:
        "При переключении цели после убийства в VATS ваша следующая (1) цель получает на 10% больше урона",
      title: "Мастерство стрельбы",
      levelRequirment: 50,
      iconSource: "",
      modificator: 1,
      modificatorStep: 1,
      sideModificator: 10,
      sideModificatorStep: 10,
      selectedStars: 0,
    },
  ];

  constructor() {
    makeAutoObservable(this);
  }
}

export default new Agility();
