import { makeAutoObservable } from "mobx";

import { IPerk } from "../entities/Perk";

class Charisma {
  perkList: IPerk[] = [
    {
      perkId: "inspirational",
      cost: 1,
      totalAmountOfStars: 3,
      description: "Находясь в группе вы получаете на 5% больше опыта",
      title: "Прирожденный лидер",
      levelRequirment: 2,
      iconSource: "",
      modificator: 5,
      modificatorStep: 5,
      selectedStars: 0,
    },
    {
      perkId: "happyCamper",
      cost: 1,
      totalAmountOfStars: 2,
      description:
        "Голод и жажда наступают на 40% медленнее, если вы находитесь в C.A.M.P",
      title: "Весёлый турист",
      levelRequirment: 3,
      iconSource: "",
      modificator: 40,
      modificatorStep: 40,
      selectedStars: 0,
    },
    {
      perkId: "loneWanderer",
      cost: 1,
      totalAmountOfStars: 3,
      description:
        "Путешествуя в одиночку, вы получаете на 10% меньше урона и ваши очки действия восстанавливаются на 10% быстрее",
      title: "Одинокий путник",
      levelRequirment: 4,
      iconSource: "",
      modificator: 10,
      modificatorStep: 5,
      sideModificator: 10,
      sideModificatorStep: 10,
      initialCost: 2,
      selectedStars: 0,
    },
    {
      perkId: "bodyguards",
      cost: 1,
      totalAmountOfStars: 4,
      description:
        "Вы получаете *6 к сопротивлению физическому и энергетическому урону за каждого напарника в команде, не учитывая вас",
      title: "Телохранители",
      levelRequirment: 5,
      iconSource: "",
      modificator: 18,
      modificatorStep: 6,
      selectedStars: 0,
    },
    {
      perkId: "hardBargain",
      cost: 1,
      totalAmountOfStars: 3,
      description:
        "Вы получаете +3 к харизме во время бартера (цены на продажу и покупку становятся лучше)",
      title: "Любитель поторговаться",
      levelRequirment: 7,
      iconSource: "",
      modificator: 3,
      modificatorStep: 3,
      selectedStars: 0,
    },
    {
      perkId: "EMT",
      cost: 1,
      totalAmountOfStars: 3,
      description:
        "Игроки воскрешенные вами получают ускорение восстановления здоровья в течение 15 секунд",
      title: "Скорая помощь",
      levelRequirment: 9,
      iconSource: "",
      modificator: 15,
      modificatorStep: 15,
      maxModificatorStep: 60,
      selectedStars: 0,
    },
    {
      perkId: "bloodsucker",
      cost: 1,
      totalAmountOfStars: 3,
      description:
        "Пакеты с кровью теперь утоляют жажду, более не заражают радиацией и восстанавливают на 50% больше здоровья",
      title: "Кровосос",
      levelRequirment: 11,
      iconSource: "",
      modificator: 50,
      modificatorStep: 50,
      selectedStars: 0,
    },
    {
      perkId: "magneticPersonality",
      cost: 1,
      totalAmountOfStars: 2,
      description:
        "Вы получаете +1 к харизме за каждого члена команды, не включая вас",
      title: "Притягательная личность",
      levelRequirment: 13,
      iconSource: "",
      modificator: 1,
      modificatorStep: 1,
      selectedStars: 0,
    },
    {
      perkId: "fieldSurgeon",
      cost: 1,
      totalAmountOfStars: 1,
      description: "Стимпаки и антирады начинают действовать гораздо быстрее",
      title: "Полевой хирург",
      levelRequirment: 15,
      iconSource: "",
      modificator: 1,
      modificatorStep: 1,
      selectedStars: 0,
      initialCost: 2,
    },
    {
      perkId: "happyGoLucky",
      cost: 1,
      totalAmountOfStars: 2,
      description:
        "Ваша удача увеличивается на 2 пока вы находитесь под алкогольным опъянением",
      title: "Беззаботность",
      levelRequirment: 17,
      iconSource: "",
      modificator: 2,
      modificatorStep: 1,
      selectedStars: 0,
    },
    {
      perkId: "injector",
      cost: 1,
      totalAmountOfStars: 3,
      description:
        "Игроки воскрешенные вами также получают +6 к восстановлению очков действий на 10 минут",
      title: "Инъектор",
      levelRequirment: 19,
      iconSource: "",
      modificator: 6,
      modificatorStep: 6,
      selectedStars: 0,
    },
    {
      perkId: "teamMedic",
      cost: 1,
      totalAmountOfStars: 3,
      description:
        "Применение вами стимпаков также подлечивает членов вашей команды на 50% от их силы",
      title: "Командный медик",
      levelRequirment: 20,
      iconSource: "",
      modificator: 50,
      modificatorStep: 25,
      selectedStars: 0,
    },
    {
      perkId: "quackSurgeon",
      cost: 1,
      totalAmountOfStars: 1,
      description: "Вы можете воскрешать напарников алкоголем",
      title: "Хирург-шарлатан",
      levelRequirment: 22,
      iconSource: "",
      modificator: 1,
      modificatorStep: 1,
      selectedStars: 0,
    },
    {
      perkId: "partyBoyGirl",
      cost: 1,
      totalAmountOfStars: 2,
      description: "Позитивные эффекты от довоенного алкоголя увеличены вдвое",
      getCustomDescription:
        "Позитивные эффекты от довоенного алкоголя увеличены втрое",
      title: "Тусовщик",
      levelRequirment: 24,
      iconSource: "",
      modificator: 2,
      modificatorStep: 1,
      selectedStars: 0,
      initialCost: 2,
    },
    {
      perkId: "travelAgent",
      cost: 1,
      totalAmountOfStars: 1,
      description:
        "Вы платите на 30% крышек меньше от изначальной стоимости быстрого перемещния",
      title: "Турагент",
      levelRequirment: 26,
      iconSource: "",
      modificator: 1,
      modificatorStep: 1,
      selectedStars: 0,
    },
    {
      perkId: "healingHands",
      cost: 1,
      totalAmountOfStars: 1,
      description:
        "Игроки воскрешенные вами излечиваются полностью от радиации",
      title: "Лечащие руки",
      levelRequirment: 28,
      iconSource: "",
      modificator: 1,
      modificatorStep: 1,
      selectedStars: 0,
    },
    {
      perkId: "animalFriend",
      cost: 1,
      totalAmountOfStars: 3,
      description:
        "В режиме прицеливания вы получаете возможность приручить животное меньше вас уровнем с 25% шансом",
      title: "Друг животных",
      levelRequirment: 30,
      iconSource: "",
      modificator: 25,
      modificatorStep: 25,
      selectedStars: 0,
    },
    {
      perkId: "overlyGenerous",
      cost: 1,
      totalAmountOfStars: 2,
      description:
        "Будучи облученным, ваши атаки ближнего боя могут с некоторым шансом нанести 25 урона радиацией противнику",
      title: "Излишне щедрый",
      levelRequirment: 32,
      iconSource: "",
      modificator: 25,
      modificatorStep: 25,
      selectedStars: 0,
    },
    {
      perkId: "antiEpidemic",
      cost: 1,
      totalAmountOfStars: 2,
      description:
        "Когда вы излечиваетесь от болезней, есть 50% шанс излечить близлежайших соратников в группе",
      title: "Борьба с эпидемией",
      levelRequirment: 34,
      iconSource: "",
      modificator: 50,
      modificatorStep: 50,
      selectedStars: 0,
    },
    {
      perkId: "spiritualHealer",
      cost: 1,
      totalAmountOfStars: 3,
      description:
        "Вы восстанавливаете здоровье в течение 5 секунд после воскрешения другого игрока",
      getCustomDescription:
        "Вы восстанавливаете здоровье в течение 10 секунд после воскрешения другого игрока",
      title: "Духовный целитель",
      levelRequirment: 36,
      iconSource: "",
      modificator: 5,
      modificatorStep: 2,
      selectedStars: 0,
    },
    {
      perkId: "squadManuevers",
      cost: 1,
      totalAmountOfStars: 2,
      description:
        "Вы передвигаетесь на 10% быстрее, когда вы находитесь в команде",
      title: "Отрядные манёвры",
      levelRequirment: 37,
      iconSource: "",
      modificator: 10,
      modificatorStep: 10,
      selectedStars: 0,
    },
    {
      perkId: "philanthropist",
      cost: 1,
      totalAmountOfStars: 3,
      description:
        "Употребляя напитки или еду вы также утоляете жажду или голод напарников в команде",
      title: "Филантроп",
      levelRequirment: 39,
      iconSource: "",
      modificator: 10,
      modificatorStep: 10,
      selectedStars: 0,
    },
    {
      perkId: "suppressor",
      cost: 1,
      totalAmountOfStars: 3,
      description: "Ваши цели наносят на 10% меньше урона после ваших атак",
      title: "Глушитель",
      levelRequirment: 40,
      iconSource: "",
      modificator: 10,
      modificatorStep: 10,
      selectedStars: 0,
    },
    {
      perkId: "strangeInNumbers",
      cost: 1,
      totalAmountOfStars: 1,
      description:
        "Положительные эффекты мутаций на 25% сильнее, если союзники в команде также имеют мутации",
      title: "Толпа странных",
      levelRequirment: 42,
      iconSource: "",
      modificator: 1,
      modificatorStep: 1,
      selectedStars: 0,
    },
    {
      perkId: "radSponge",
      cost: 1,
      totalAmountOfStars: 3,
      description:
        "Будучи радиоактивно зараженным, периодически вы будете излечивать ближайших союзников от 80 единиц радиации",
      title: "Поглотитель радиации",
      levelRequirment: 44,
      iconSource: "",
      modificator: 80,
      modificatorStep: 60,
      selectedStars: 0,
    },
    {
      perkId: "tenderizer",
      cost: 1,
      totalAmountOfStars: 3,
      description:
        "Ваши цели получают на 5% больше урона в течение 5 секунд после вашей атаки",
      getCustomDescription:
        "Ваши цели получают на 10% больше урона в течение 10 секунд после вашей атаки",
      title: "Отбивной молоток",
      levelRequirment: 46,
      iconSource: "",
      modificator: 5,
      modificatorStep: 2,
      sideModificator: 5,
      sideModificatorStep: 2,
      selectedStars: 0,
    },
    {
      perkId: "friendlyFire",
      cost: 1,
      totalAmountOfStars: 3,
      description:
        "Союзники которых вы задеваете огнем (не включая коктейли молотова), восстанавливают 6 ед. здоровья в течение 2 секунд",
      title: "Дружественный огонь",
      levelRequirment: 48,
      iconSource: "",
      modificator: 6,
      modificatorStep: 3,
      selectedStars: 0,
    },
    {
      perkId: "wastelandWhisperer",
      cost: 1,
      totalAmountOfStars: 3,
      description:
        "В режиме прицеливания вы получаете возможность приручить любое существо меньше вас уровнем с 25% шансом",
      title: "Говорящий с пустошью",
      levelRequirment: 50,
      iconSource: "",
      modificator: 25,
      modificatorStep: 25,
      selectedStars: 0,
    },
  ];

  constructor() {
    makeAutoObservable(this);
  }
}

export default new Charisma();
