import { makeAutoObservable } from "mobx";

import { IPerk } from "../entities/Perk";

class Endurance {
  perkList: IPerk[] = [
    {
      perkId: "leadBelly",
      cost: 1,
      totalAmountOfStars: 3,
      description:
        "Вы получаете на 30% меньше радиации при употреблении пищи и воды",
      title: "Свинцовое брюхо",
      levelRequirment: 2,
      iconSource: "",
      modificator: 30,
      modificatorStep: 30,
      maxModificatorStep: 100,
      selectedStars: 0,
    },
    {
      perkId: "dromedary",
      cost: 1,
      totalAmountOfStars: 3,
      description: "Все напитки утоляют жажду на 25% эффективнее",
      title: "Верблюд",
      levelRequirment: 3,
      iconSource: "",
      modificator: 25,
      modificatorStep: 25,
      selectedStars: 0,
    },
    {
      perkId: "ironStomach",
      cost: 1,
      totalAmountOfStars: 3,
      description: "Шанс заразиться от приёма пищи уменьшен на 30% ",
      title: "Железный желудок",
      levelRequirment: 4,
      iconSource: "",
      modificator: 30,
      modificatorStep: 30,
      selectedStars: 0,
    },
    {
      perkId: "slowMetabolizer",
      cost: 1,
      totalAmountOfStars: 3,
      description: "Вся пища утоляет голод на 25% эффективнее",
      title: "Медленный метаболизм",
      levelRequirment: 5,
      iconSource: "",
      modificator: 25,
      modificatorStep: 25,
      selectedStars: 0,
    },
    {
      perkId: "thirstQuencher",
      cost: 1,
      totalAmountOfStars: 3,
      description: "Шанс заразиться от выпитых напитков уменьшен на 30% ",
      title: "Утолитель жажды",
      levelRequirment: 6,
      iconSource: "",
      modificator: 30,
      modificatorStep: 30,
      selectedStars: 0,
    },
    {
      perkId: "goodDoggy",
      cost: 1,
      totalAmountOfStars: 1,
      description: "Увеличивает эффективность собачьих консервов в три раза",
      title: "Хороший пёсик",
      levelRequirment: 8,
      iconSource: "",
      modificator: 3,
      modificatorStep: 1,
      selectedStars: 0,
    },
    {
      perkId: "naturalResistance",
      cost: 1,
      totalAmountOfStars: 3,
      description: "Шанс заразиться от окружающей среды уменьшен на 30%",
      title: "Естественная сопротивляемость",
      levelRequirment: 10,
      iconSource: "",
      modificator: 30,
      modificatorStep: 30,
      selectedStars: 0,
    },
    {
      perkId: "hydroFix",
      cost: 1,
      totalAmountOfStars: 2,
      description: "Употребление химии вызывает на 50%  меньше жажды",
      title: "Подавление жажды",
      levelRequirment: 11,
      iconSource: "",
      modificator: 50,
      modificatorStep: 50,
      selectedStars: 0,
    },
    {
      perkId: "rejuvenated",
      cost: 1,
      totalAmountOfStars: 2,
      description:
        "Вы получаете увеличенные бонусы от эффектов сытости и гидратации",
      title: "Обновленный",
      levelRequirment: 12,
      iconSource: "",
      modificator: 1,
      modificatorStep: 1,
      selectedStars: 0,
    },
    {
      perkId: "colaNut",
      cost: 1,
      totalAmountOfStars: 2,
      description: "Вы получаете двойные бонусы от ядер-колы",
      title: "Супер-кола",
      levelRequirment: 14,
      iconSource: "",
      modificator: 1,
      modificatorStep: 1,
      getCustomDescription: "Вы получаете утроенные бонусы от ядер-колы",
      selectedStars: 0,
    },
    {
      perkId: "cannibal",
      cost: 1,
      totalAmountOfStars: 3,
      description:
        "Поедая трупы гулей, супер-мутантов, горелых, и кротов-шахтёров вы восстанавливаете здоровье и голод",
      title: "Каннибал",
      levelRequirment: 15,
      iconSource: "",
      modificator: 1,
      modificatorStep: 1,
      selectedStars: 0,
    },
    {
      perkId: "vaccinated",
      cost: 1,
      totalAmountOfStars: 3,
      description: "Шанс заразиться болезнями от существ уменьшен на 30%",
      title: "Вакцинация",
      levelRequirment: 16,
      iconSource: "",
      modificator: 30,
      modificatorStep: 30,
      selectedStars: 0,
    },
    {
      perkId: "munchyResistance",
      cost: 1,
      totalAmountOfStars: 2,
      description: "Шанс получить зависимость от препарата уменьшен на 50%",
      title: "Чистая жизнь",
      levelRequirment: 17,
      iconSource: "",
      modificator: 50,
      modificatorStep: 50,
      selectedStars: 0,
    },
    {
      perkId: "homebody",
      cost: 1,
      totalAmountOfStars: 2,
      description: "Вы регенерируете здоровье, пока вы находитесь в CAMP",
      title: "Домосед",
      levelRequirment: 19,
      iconSource: "",
      modificator: 50,
      modificatorStep: 50,
      getCustomDescription:
        "Вы регенерируете здоровье и конечности быстрее, пока вы находитесь в CAMP",
      selectedStars: 0,
    },
    {
      perkId: "adamantiumSkeleton",
      cost: 1,
      totalAmountOfStars: 2,
      description: "Ваши конечности получают на 30% меньше урона",
      title: "Алмазный скелет",
      levelRequirment: 21,
      iconSource: "",
      modificator: 30,
      modificatorStep: 30,
      getCustomDescription: "Ваши конечности не получают урона",
      selectedStars: 0,
    },
    {
      perkId: "solarPowered",
      cost: 1,
      totalAmountOfStars: 3,
      description:
        "Вы получаете +1 к силе и выносливости между 6 утра и 6 вечера.",
      title: "Солнечная батарейка",
      levelRequirment: 22,
      iconSource: "",
      modificator: 1,
      modificatorStep: 1,
      selectedStars: 0,
    },
    {
      perkId: "chemFiend",
      cost: 1,
      totalAmountOfStars: 3,
      description: "Эффекты от употребления химии на 30% дольше",
      title: "Чёрт на препаратах",
      levelRequirment: 23,
      iconSource: "",
      modificator: 30,
      modificatorStep: 30,
      getCustomDescription: "Эффекты от употребления химии в два раза дольше",
      selectedStars: 0,
    },
    {
      perkId: "aquaboy",
      cost: 1,
      totalAmountOfStars: 1,
      description:
        "Вы больше не получаете радиации от плавания в воде и можете дышать под водой.",
      title: "Аквамальчик/Аквадевочка",
      levelRequirment: 26,
      iconSource: "",
      modificator: 1,
      modificatorStep: 1,
      selectedStars: 0,
    },
    {
      perkId: "fireproof",
      cost: 1,
      totalAmountOfStars: 3,
      description: "Вы получаете на 15% меньше урона от взрывов и урона огнем",
      title: "Огнеупорный",
      levelRequirment: 27,
      iconSource: "",
      modificator: 15,
      modificatorStep: 15,
      selectedStars: 0,
    },
    {
      perkId: "nocturnalFortitude",
      cost: 1,
      totalAmountOfStars: 2,
      description:
        "Вы получаете 20 единиц к максимальному здоровью между 6 вечера и 6 утра",
      title: "Ночная отвага",
      levelRequirment: 29,
      iconSource: "",
      modificator: 20,
      modificatorStep: 20,
      selectedStars: 0,
    },
    {
      perkId: "ironclad",
      cost: 1,
      totalAmountOfStars: 5,
      description:
        "Вы получаете +10 к сопротивлению обычному и энергетическому урону , если не носите силовой брони",
      title: "Броненосец",
      levelRequirment: 30,
      iconSource: "",
      modificator: 10,
      modificatorStep: 10,
      selectedStars: 0,
    },
    {
      perkId: "revenant",
      cost: 1,
      totalAmountOfStars: 2,
      description:
        "Вы получаете +25% к урону на две минуты после воскрешения другим игроком",
      title: "Выживший",
      levelRequirment: 32,
      iconSource: "",
      modificator: 25,
      modificatorStep: 25,
      selectedStars: 0,
    },
    {
      perkId: "radResistant",
      cost: 1,
      totalAmountOfStars: 4,
      description: "Вы получаете +10 к сопротивлению радиации",
      title: "Рад-сопротивляемость",
      levelRequirment: 34,
      iconSource: "",
      modificator: 10,
      modificatorStep: 10,
      selectedStars: 0,
    },
    {
      perkId: "ghoulish",
      cost: 1,
      totalAmountOfStars: 3,
      description:
        "Радиоактивное облучение восстанавливает вам по 0.5 здоровья за каждую 1 единицу урона от радиации",
      title: "Гулификация",
      levelRequirment: 36,
      iconSource: "",
      modificator: 0.5,
      modificatorStep: 0.5,
      selectedStars: 0,
    },
    {
      perkId: "radicool",
      cost: 1,
      totalAmountOfStars: 1,
      description:
        "Чем больше вы радиоактивны - тем больше ваша сила (+5 макс.)",
      title: "Радикрутость",
      levelRequirment: 38,
      iconSource: "",
      modificator: 1,
      modificatorStep: 1,
      selectedStars: 0,
    },
    {
      perkId: "professionalDrinker",
      cost: 3,
      totalAmountOfStars: 1,
      description: "У вас нет шанса получить алкогольную зависимость",
      title: "Профессиональный алкоголик",
      levelRequirment: 39,
      iconSource: "",
      modificator: 1,
      modificatorStep: 1,
      selectedStars: 0,
    },
    {
      perkId: "allNightLong",
      cost: 1,
      totalAmountOfStars: 3,
      description: "Жажда и голод наступают на 20% медленнее ночью",
      title: "Всю ночь",
      levelRequirment: 41,
      iconSource: "",
      modificator: 20,
      modificatorStep: 20,
      selectedStars: 0,
    },
    {
      perkId: "chemResistant",
      cost: 1,
      totalAmountOfStars: 3,
      description: "Шанс получить зависимость от препаратов на 50% меньше",
      title: "Чистая жизнь",
      levelRequirment: 43,
      iconSource: "",
      modificator: 50,
      modificatorStep: 50,
      getCustomDescription:
        "Вы получаете иммунитет к зависимости от препаратов",
      selectedStars: 0,
    },
    {
      perkId: "sunKissed",
      cost: 1,
      totalAmountOfStars: 2,
      description:
        "Вы медленно восстанавливаетесь от радиации между 6 утра и 6 вечера",
      title: "Поцелованный солнцем",
      levelRequirment: 45,
      iconSource: "",
      modificator: 1,
      modificatorStep: 1,
      getCustomDescription:
        "Вы быстрее восстанавливаетесь от радиации между 6 утра и 6 вечера",
      selectedStars: 0,
    },
    {
      perkId: "photoSynthetic",
      cost: 1,
      totalAmountOfStars: 2,
      description:
        "Вы медленно восстанавливаете здоровье между 6 утра и 6 вечера",
      title: "Фотосинтез",
      levelRequirment: 47,
      iconSource: "",
      modificator: 1,
      modificatorStep: 1,
      getCustomDescription:
        "Вы быстрее восстанавливаете здоровье между 6 утра и 6 вечера",
      selectedStars: 0,
    },
    {
      perkId: "lifegiver",
      cost: 1,
      totalAmountOfStars: 4,
      description: "Вы получаете +15 к максимальному здоровью",
      title: "Фонтан жизни",
      levelRequirment: 50,
      iconSource: "",
      modificator: 15,
      modificatorStep: 15,
      selectedStars: 0,
      initialCost: 2,
    },
  ];

  constructor() {
    makeAutoObservable(this);
  }
}

export default new Endurance();
