import { create } from "zustand";

import { PerkStoreData } from "../types/Perk";
import { SPECIALS } from "../entities/Specials";

export const usePerceptionStore = create<PerkStoreData>((set) => ({
  perkList: [
    {
      perkId: "concetratedFire",
      cost: 1,
      totalAmountOfStars: 3,
      description:
        "Вы получаете возможность выбирать через VATS конечности противников, также ваш урон увеличивается на 0.1, точность увеличивается на 10% при стрельбе через VATS",
      title: "Массированный огонь",
      levelRequirment: 2,
      iconSource: "",
      modificator: 10,
      modificatorStep: 5,
      sideModificator: 0.01,
      sideModificatorStep: 0.01,
      selectedStars: 0,
    },
    {
      perkId: "rifleman",
      cost: 1,
      totalAmountOfStars: 3,
      description: "Неавтоматические карабины наносят на 10% больше урона",
      title: "Стрелок из карабинов",
      levelRequirment: 2,
      iconSource: "",
      modificator: 10,
      modificatorStep: 5,
      selectedStars: 0,
    },
    {
      perkId: "archer",
      cost: 1,
      totalAmountOfStars: 3,
      description: "Луки и арбалеты наносят на 10% больше урона",
      title: "Лучник",
      levelRequirment: 2,
      iconSource: "",
      modificator: 10,
      modificatorStep: 5,
      selectedStars: 0,
    },
    {
      perkId: "butchersBounty",
      cost: 1,
      totalAmountOfStars: 3,
      description: "Шанс выпадения мяса из трупа животного увеличен на 40%",
      title: "Награда мясника",
      levelRequirment: 3,
      iconSource: "",
      modificator: 40,
      modificatorStep: 20,
      selectedStars: 0,
    },
    {
      perkId: "greenThumb",
      cost: 1,
      totalAmountOfStars: 1,
      description: "Вы собираете в два раза больше растений",
      title: "Садовник",
      levelRequirment: 4,
      iconSource: "",
      modificator: 2,
      modificatorStep: 1,
      selectedStars: 0,
    },
    {
      perkId: "picklock",
      cost: 1,
      totalAmountOfStars: 1,
      description: "Область успешного взлома больше на 10%",
      title: "Взломщик",
      levelRequirment: 5,
      iconSource: "",
      modificator: 10,
      modificatorStep: 1,
      selectedStars: 0,
    },
    {
      perkId: "commando",
      cost: 1,
      totalAmountOfStars: 3,
      description: "Автоматическое оружие наносит на 10% больше урона",
      title: "Коммандос",
      levelRequirment: 5,
      iconSource: "",
      modificator: 10,
      modificatorStep: 5,
      selectedStars: 0,
    },
    {
      perkId: "fireInTheHole",
      cost: 1,
      totalAmountOfStars: 3,
      description:
        "При броске вы видите линию полёта метаемого снаряда, ваши снаряды летят на 15% дальше",
      title: "Ложись!",
      levelRequirment: 5,
      iconSource: "",
      modificator: 15,
      modificatorStep: 15,
      maxModificatorStep: 50,
      selectedStars: 0,
    },
    {
      perkId: "bowBeforeMe",
      cost: 1,
      totalAmountOfStars: 3,
      description:
        "Ваши стрелы из лука и арбалета игнорируют 12% брони и имеют 3% шанс ошеломить противника",
      title: "Талантливый лучник",
      levelRequirment: 6,
      iconSource: "",
      modificator: 12,
      modificatorStep: 12,
      sideModificator: 3,
      sideModificatorStep: 3,
      selectedStars: 0,
    },
    {
      perkId: "crackShot",
      cost: 1,
      totalAmountOfStars: 3,
      description:
        "При стрельбе из пистолета в режиме прицеливания вы получаете на 10% больше дальнобойности и увеличенную точность",
      title: "Прирожденный стрелок",
      levelRequirment: 7,
      iconSource: "",
      modificator: 10,
      modificatorStep: 10,
      perkData: {
        firstStarModificator: 0.85,
        secondStarModificator: 0.7,
        thirdStarModificator: 0.55,
      },
      selectedStars: 0,
    },
    {
      perkId: "skeetShooter",
      cost: 1,
      totalAmountOfStars: 3,
      description:
        "Ваша стрельба из дробовика имеет улучшению точность и уменьшенный разброс",
      title: "Стрельба по тарелкам",
      levelRequirment: 10,
      iconSource: "",
      modificator: 0,
      modificatorStep: 0,
      perkData: {
        firstStarModificator: 0.85,
        secondStarModificator: 0.7,
        thirdStarModificator: 0.55,
      },
      selectedStars: 0,
    },
    {
      perkId: "expertRifleman",
      cost: 1,
      totalAmountOfStars: 3,
      description: "Неавтоматические карабины наносят на 10% больше урона",
      title: "Эксперт по карабинам",
      levelRequirment: 10,
      iconSource: "",
      modificator: 10,
      modificatorStep: 5,
      selectedStars: 0,
    },
    {
      perkId: "pannapictagraphist",
      cost: 1,
      totalAmountOfStars: 1,
      description:
        "У вас чутье на журналы, вы слышите специальный аудиосигнал когда рядом с вами есть журнал",
      title: "Коллекционер журналов",
      levelRequirment: 12,
      iconSource: "",
      modificator: 1,
      modificatorStep: 1,
      selectedStars: 0,
    },
    {
      perkId: "exterminator",
      cost: 1,
      totalAmountOfStars: 3,
      description: "Вы игнорируете 25% брони любого насекомого",
      title: "Дезинсектор",
      levelRequirment: 14,
      iconSource: "",
      modificator: 25,
      modificatorStep: 25,
      selectedStars: 0,
    },
    {
      perkId: "expertArcher",
      cost: 1,
      totalAmountOfStars: 3,
      description: "Ваши луки и арбалеты наносят на 10% больше урона",
      title: "Эксперт лучник",
      levelRequirment: 15,
      iconSource: "",
      modificator: 10,
      modificatorStep: 5,
      selectedStars: 0,
    },
    {
      perkId: "perceptiBobble",
      cost: 1,
      totalAmountOfStars: 1,
      description:
        "У вас чутье на пупсов, вы слышите специальный аудиосигнал когда рядом с вами есть пупс",
      title: "Пупсолокатор",
      levelRequirment: 16,
      iconSource: "",
      modificator: 1,
      modificatorStep: 1,
      selectedStars: 0,
    },
    {
      perkId: "groundPounder",
      cost: 1,
      totalAmountOfStars: 3,
      description:
        "Вы перезаряжаете винтовки на 10% быстрее, ваша точность при стрельбе от бедра повышает",
      title: "Пехотинец",
      levelRequirment: 18,
      iconSource: "",
      modificator: 10,
      modificatorStep: 10,
      sideModificator: 0.85,
      sideModificatorStep: 0.15,
      selectedStars: 0,
    },
    {
      perkId: "expertPicklock",
      cost: 1,
      totalAmountOfStars: 1,
      description: "Область успешного взлома больше на 10%, +1 к навыку взлома",
      title: "Опытный взломщик",
      levelRequirment: 19,
      iconSource: "",
      modificator: 1,
      modificatorStep: 1,
      selectedStars: 0,
    },
    {
      perkId: "awareness",
      cost: 2,
      totalAmountOfStars: 1,
      description:
        "Интерфейс режима VATS показывает дополнительную информацию о сопротивлениях противника",
      title: "Осведомленность",
      levelRequirment: 20,
      iconSource: "",
      modificator: 1,
      modificatorStep: 1,
      selectedStars: 0,
    },
    {
      perkId: "expertCommando",
      cost: 1,
      totalAmountOfStars: 3,
      description: "Автоматическое оружие наносит на 10% больше урона",
      title: "Эксперт коммандос",
      levelRequirment: 20,
      iconSource: "",
      modificator: 10,
      modificatorStep: 5,
      selectedStars: 0,
    },
    {
      perkId: "fortuneFinder",
      cost: 1,
      totalAmountOfStars: 1,
      description:
        "Вы получаете возможность слышать аудиосигнал, когда поблизости есть тайник с крышками",
      title: "Кладоискатель",
      levelRequirment: 22,
      iconSource: "",
      modificator: 1,
      modificatorStep: 1,
      selectedStars: 0,
    },
    {
      perkId: "nightPerson",
      cost: 1,
      totalAmountOfStars: 3,
      description:
        "Вы получаете +1 к интеллекту и восприятию во временной интервал между с 6ч вечера и до 6ч утра",
      title: "Ночное существо",
      levelRequirment: 24,
      iconSource: "",
      modificator: 1,
      modificatorStep: 1,
      selectedStars: 0,
    },
    {
      perkId: "sniper",
      cost: 1,
      totalAmountOfStars: 3,
      description:
        "Вы получаете возможность удерживать дыхание в режиме прицеливания на 25% дольше",
      title: "Снайпер",
      levelRequirment: 28,
      iconSource: "",
      modificator: 25,
      modificatorStep: 25,
      selectedStars: 0,
    },
    {
      perkId: "tankKiller",
      cost: 1,
      totalAmountOfStars: 3,
      description:
        "Ваши пистолеты и винтовки игнорируют 12% брони противника и имеют 3% шанс ошеломления",
      title: "Убийца танков",
      levelRequirment: 30,
      iconSource: "",
      modificator: 12,
      modificatorStep: 12,
      sideModificator: 3,
      sideModificatorStep: 3,
      selectedStars: 0,
    },
    {
      perkId: "refractor",
      cost: 1,
      totalAmountOfStars: 4,
      description: "Вы получаете +10 к сопротивлению энерго урону",
      title: "Отражатель",
      levelRequirment: 32,
      iconSource: "",
      modificator: 10,
      modificatorStep: 10,
      selectedStars: 0,
    },
    {
      perkId: "glowSight",
      cost: 1,
      totalAmountOfStars: 3,
      description: "Вы наносите на 20% больше урона светящимся противникам",
      title: "Прицел с подсветкой",
      levelRequirment: 33,
      iconSource: "",
      modificator: 20,
      modificatorStep: 20,
      selectedStars: 0,
    },
    {
      perkId: "masterRifleman",
      cost: 1,
      totalAmountOfStars: 3,
      description: "Неавтоматические карабины наносят на 10% больше урона",
      title: "Мастер стрелок из карабина",
      levelRequirment: 35,
      iconSource: "",
      modificator: 10,
      modificatorStep: 5,
      selectedStars: 0,
    },
    {
      perkId: "grenadier",
      cost: 1,
      totalAmountOfStars: 2,
      description: "Радиус поражения у вашей взрывчатки увеличен на 50%",
      title: "Гренадёр",
      levelRequirment: 35,
      iconSource: "",
      modificator: 50,
      modificatorStep: 50,
      selectedStars: 0,
    },
    {
      perkId: "masterArcher",
      cost: 1,
      totalAmountOfStars: 3,
      description: "Ваши луки и арбалеты наносят на 10% больше урона",
      title: "Мастер лучник",
      levelRequirment: 35,
      iconSource: "",
      modificator: 10,
      modificatorStep: 5,
      selectedStars: 0,
    },
    {
      perkId: "longShot",
      cost: 1,
      totalAmountOfStars: 3,
      description:
        "Винтовки в режиме прицеливания получают +10% к дальности боя и точности",
      title: "Выстрел с дистанции",
      levelRequirment: 37,
      iconSource: "",
      modificator: 10,
      modificatorStep: 10,
      selectedStars: 0,
    },
    {
      perkId: "masterLockPick",
      cost: 1,
      totalAmountOfStars: 1,
      description: "Область успешного взлома больше на 10%, +1 к навыку взлома",
      title: "Эксперт взломщик",
      levelRequirment: 40,
      iconSource: "",
      modificator: 1,
      modificatorStep: 1,
      selectedStars: 0,
    },
    {
      perkId: "masterCommando",
      cost: 1,
      totalAmountOfStars: 3,
      description: "Автоматическое оружие наносит на 10% больше урона",
      title: "Мастер коммандос",
      levelRequirment: 40,
      iconSource: "",
      modificator: 10,
      modificatorStep: 5,
      selectedStars: 0,
    },
    {
      perkId: "nightEyes",
      cost: 2,
      totalAmountOfStars: 1,
      description:
        "Вы получаете возможность ночного видения в режиме скрытности с 6 вечера до 6 утра",
      title: "Ночное зрение",
      levelRequirment: 50,
      iconSource: "",
      modificator: 1,
      modificatorStep: 1,
      selectedStars: 0,
    },
  ],
  type: SPECIALS.PERCEPTION,
  // increasePopulation: () => set((state) => ({ bears: state.bears + 1 })),
}));
