import { create } from "zustand";

import { IPerk, PerkStoreData } from "../types/Perk";
import { SPECIALS } from "../entities/Specials";

export const useStrengthStore = create<PerkStoreData>((set) => ({
  perkList: [
    {
      perkId: "gladiator",
      cost: 1,
      totalAmountOfStars: 3,
      description:
        "Ваше одноручное оружие ближнего боя наносит на 10% больше урона",
      title: "Гладиатор",
      levelRequirment: 2,
      iconSource: "",
      modificator: 10,
      modificatorStep: 5,
      selectedStars: 0,
    },
    {
      perkId: "travelingPharmacy",
      cost: 1,
      totalAmountOfStars: 3,
      description: "Вес всех препаратов (включая стимпаки) уменьшен на 30%",
      title: "Странствующая аптека",
      levelRequirment: 3,
      iconSource: "",
      modificator: 30,
      modificatorStep: 30,
      selectedStars: 0,
    },
    {
      perkId: "ironFist",
      cost: 1,
      totalAmountOfStars: 3,
      description: "Урон от ударов кулаками повышен на 10%",
      title: "Железный кулак",
      levelRequirment: 3,
      iconSource: "",
      modificator: 10,
      modificatorStep: 5,
      selectedStars: 0,
    },
    {
      perkId: "slugger",
      cost: 1,
      totalAmountOfStars: 3,
      description: "Урон от двуручного оружия ближнего боя повышен на 10%",
      title: "Мастер мощных ударов",
      levelRequirment: 6,
      iconSource: "",
      modificator: 10,
      modificatorStep: 5,
      selectedStars: 0,
    },
    {
      perkId: "packRat",
      cost: 1,
      totalAmountOfStars: 3,
      description: "Вес хлама в инвентаре снижен на 25%",
      title: "Барахольщик",
      levelRequirment: 7,
      iconSource: "",
      modificator: 25,
      modificatorStep: 25,
      selectedStars: 0,
    },
    {
      perkId: "shotGunner",
      cost: 1,
      totalAmountOfStars: 3,
      description: "Урон от дробовиков увеличен на 10%",
      title: "Стрелок из дробовика",
      levelRequirment: 10,
      iconSource: "",
      modificator: 10,
      modificatorStep: 5,
      selectedStars: 0,
    },
    {
      perkId: "basher",
      cost: 1,
      totalAmountOfStars: 2,
      description:
        "Урон прикладами увеличен на 25%, имеется 5% шанс сломать конечно противнику",
      title: "Хрясь!",
      levelRequirment: 11,
      iconSource: "",
      modificator: 25,
      modificatorStep: 25,
      sideModificator: 5,
      sideModificatorStep: 5,
      selectedStars: 0,
    },
    {
      perkId: "sturdyFrame",
      cost: 1,
      totalAmountOfStars: 2,
      description: "Вес брони переносимой в инвентаре снижается на 25%",
      title: "Прочная рама",
      levelRequirment: 13,
      iconSource: "",
      modificator: 25,
      modificatorStep: 25,
      selectedStars: 0,
    },
    {
      perkId: "barbarian",
      cost: 1,
      totalAmountOfStars: 3,
      description:
        "Каждое очко Силы добавляет +2 к сопротивлению урону (макс 40) (не работает в силовой броне)",
      title: "Варвар",
      levelRequirment: 14,
      iconSource: "",
      modificator: 2,
      modificatorStep: 1,
      sideModificator: 40,
      sideModificatorStep: 20,
      selectedStars: 0,
    },
    {
      perkId: "martialArtist",
      cost: 1,
      totalAmountOfStars: 3,
      description:
        "Ваше оружие ближнего боя весит на 20% меньше, вы сможете атаковать на 10% быстрее",
      title: "Специалист ближнего боя",
      levelRequirment: 16,
      iconSource: "",
      modificator: 20,
      modificatorStep: 20,
      sideModificator: 10,
      sideModificatorStep: 10,
      selectedStars: 0,
    },
    {
      perkId: "scatterShot",
      cost: 1,
      totalAmountOfStars: 3,
      description:
        "Дробовики весят на 30% меньше и вы перезаряжаете их на 10% быстрее",
      title: "Варвар",
      levelRequirment: 18,
      iconSource: "",
      modificator: 30,
      modificatorStep: 30,
      sideModificator: 10,
      sideModificatorStep: 10,
      selectedStars: 0,
    },
    {
      perkId: "expertGladiator",
      cost: 1,
      totalAmountOfStars: 3,
      description: "Одноручное оружие ближнего боя наносит на 10% больше урона",
      title: "Эксперт гладиатор",
      levelRequirment: 20,
      iconSource: "",
      modificator: 10,
      modificatorStep: 5,
      selectedStars: 0,
    },
    {
      perkId: "blocker",
      cost: 1,
      totalAmountOfStars: 3,
      description: "Вы получаете на 15% меньше урона в ближнем бою",
      title: "Блокировка",
      levelRequirment: 21,
      iconSource: "",
      modificator: 15,
      modificatorStep: 15,
      selectedStars: 0,
    },
    {
      perkId: "bandolier",
      cost: 1,
      totalAmountOfStars: 2,
      description: "Боеприпасы для баллистического оружия весят на 45% меньше",
      title: "Патронташ",
      levelRequirment: 22,
      iconSource: "",
      modificator: 45,
      modificatorStep: 45,
      selectedStars: 0,
    },
    {
      perkId: "expertShotgunner",
      cost: 1,
      totalAmountOfStars: 3,
      description: "Урон при стрельбе из дробовиков увеличен на 10%",
      title: "Эксперт стрелок из дробовика",
      levelRequirment: 23,
      iconSource: "",
      modificator: 10,
      modificatorStep: 5,
      selectedStars: 0,
    },
    {
      perkId: "expertSlugger",
      cost: 1,
      totalAmountOfStars: 3,
      description: "Урон двуручным оружием ближнего боя увеличен на 10%",
      title: "Эксперт по мощным ударам",
      levelRequirment: 24,
      iconSource: "",
      modificator: 10,
      modificatorStep: 5,
      selectedStars: 0,
    },
    {
      perkId: "strongBack",
      cost: 1,
      totalAmountOfStars: 4,
      description: "Увеличивает переносимый вес на 10 фунтов",
      title: "Крепкий хребет",
      levelRequirment: 26,
      iconSource: "",
      modificator: 10,
      modificatorStep: 10,
      selectedStars: 0,
    },
    {
      perkId: "heavyGunner",
      cost: 1,
      totalAmountOfStars: 4,
      description:
        "Ваше невзрывное тяжелое оружие наносит теперь на 10% больше урона",
      title: "Фанат больших пушек",
      levelRequirment: 30,
      iconSource: "",
      modificator: 10,
      modificatorStep: 5,
      selectedStars: 0,
    },
    {
      perkId: "ordnanceExpress",
      cost: 1,
      totalAmountOfStars: 3,
      description: "Уменьшает метаемой вес взрывчатки на 30%",
      title: "Сверхбыстрый боезаряд",
      levelRequirment: 31,
      iconSource: "",
      modificator: 30,
      modificatorStep: 30,
      selectedStars: 0,
    },
    {
      perkId: "fullCharge",
      cost: 1,
      totalAmountOfStars: 2,
      description:
        "При ускорении в силовой броне расходуется на 50% меньше энергии ядерных блоков",
      title: "Полный заряд",
      levelRequirment: 33,
      iconSource: "",
      modificator: 50,
      modificatorStep: 50,
      selectedStars: 0,
    },
    {
      perkId: "incisor",
      cost: 1,
      totalAmountOfStars: 3,
      description: "Снижение эффективности защиты брони противника на 25%",
      title: "Резец",
      levelRequirment: 34,
      iconSource: "",
      modificator: 25,
      modificatorStep: 25,
      selectedStars: 0,
    },
    {
      perkId: "bearArms",
      cost: 1,
      totalAmountOfStars: 3,
      description: "Тяжелое оружие весит меньше на 30%",
      title: "Медвежьи лапищи",
      levelRequirment: 35,
      iconSource: "",
      modificator: 30,
      modificatorStep: 30,
      selectedStars: 0,
    },
    {
      perkId: "lockAndLoad",
      cost: 1,
      totalAmountOfStars: 3,
      description: "Тяжелое оружие перезаряжается на 10% быстрее",
      title: "Полная боеготовность",
      levelRequirment: 37,
      iconSource: "",
      modificator: 10,
      modificatorStep: 10,
      selectedStars: 0,
    },
    {
      perkId: "bulletShield",
      cost: 1,
      totalAmountOfStars: 3,
      description:
        "Вы получаете +20 к сопротивлению урону во время стрельбы из тяжелого оружия",
      title: "Щит",
      levelRequirment: 39,
      iconSource: "",
      modificator: 20,
      modificatorStep: 20,
      selectedStars: 0,
    },
    {
      perkId: "expertHeavyGunner",
      cost: 1,
      totalAmountOfStars: 3,
      description:
        "Ваше баллистическое(не взрывное) тяжелое оружие наносит на 10% больше урона",
      title: "Эскперт больших пушек",
      levelRequirment: 40,
      iconSource: "",
      modificator: 10,
      modificatorStep: 5,
      selectedStars: 0,
    },
    {
      perkId: "painTrain",
      cost: 1,
      totalAmountOfStars: 3,
      description:
        "Врезаясь с разбега в противников, находясь в силовой броне, вы наносите им урон и ошеломляете их",
      title: "Локомотив",
      levelRequirment: 41,
      iconSource: "",
      modificator: 10,
      modificatorStep: 5,
      selectedStars: 0,
    },
    {
      perkId: "masterGladiator",
      cost: 1,
      totalAmountOfStars: 3,
      description:
        "Ваше одиночное оружие ближнего боя наносит на 10% больше урона",
      title: "Локомотив",
      levelRequirment: 43,
      iconSource: "",
      modificator: 10,
      modificatorStep: 5,
      selectedStars: 0,
    },
    {
      perkId: "masterShotgunner",
      cost: 1,
      totalAmountOfStars: 3,
      description: "Дробовики наносят на 10% больше урона",
      title: "Мастер-стрелок из дробовика",
      levelRequirment: 45,
      iconSource: "",
      modificator: 10,
      modificatorStep: 5,
      selectedStars: 0,
    },
    {
      perkId: "masterSlugger",
      cost: 1,
      totalAmountOfStars: 3,
      description:
        "Ваше двуручное оружие ближнего боя наносит на 10% больше урона",
      title: "Мастер мощных ударов",
      levelRequirment: 48,
      iconSource: "",
      modificator: 10,
      modificatorStep: 5,
      selectedStars: 0,
    },
    {
      perkId: "masterHeavyGunner",
      cost: 1,
      totalAmountOfStars: 3,
      description:
        "Ваше баллистическое(не взрывное) тяжелое оружие наносит на 10% больше урона",
      title: "Мастер больших пушек",
      levelRequirment: 50,
      iconSource: "",
      modificator: 10,
      modificatorStep: 5,
      selectedStars: 0,
    },
  ],
  type: SPECIALS.STRENGTH,
  // increasePopulation: () => set((state) => ({ bears: state.bears + 1 })),
}));
